import os


ALGORITHM = os.getenv("ALGORITHM")
ENCODING = 'UTF-8'
HASH_ITERATIONS = 100000
TIME_DELTA_FOR_ACCESS = 15
TIME_DELTA_FOR_REFRESH = 30
SALT_RANDOM_BYTES = 16
SECRET_KEY = os.getenv("SECRET_KEY")
SYMBOLS_REFRESH_TOKEN = 16
