import os


ALGORITHM = os.getenv("ALGORITHM")
ENCODING = 'UTF-8'
HASH_ITERATIONS = 100000
TIME_DELTA_FOR_ACCESS = 15
TIME_DELTA_FOR_REFRESH = 30
SALT_RANDOM_BYTES = 16
SECRET_KEY = os.getenv("SECRET_KEY")
SYMBOLS_REFRESH_TOKEN = 16
# DATABASE INFO
HOST = "mysqldb"
PORT = 3307
USER = "root"
PASSWORD = "K^rb%kVQH5$1I8WvL1CQerr"
DATABASE = "auto.ru"